[package]
name = "config"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
toml.workspace = true
dirs.workspace = true
tracing.workspace = true
gpui = { workspace = true, default-features = false }
