[package]
name = "themeing"
version = "0.1.0"
edition = "2024"

[dependencies]
config = { path = "../config" }
alacritty_terminal.workspace = true
gpui = { workspace = true, default-features = false }
gpui-component.workspace = true
