[build]
rustflags = ["-C", "symbol-mangling-version=v0", "--cfg", "tokio_unstable"]
# rustc-wrapper = "sccache"

[target.'cfg(target_os = "linux")']
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.'cfg(target_os = "windows")']
rustflags = [
    "-C",
    "symbol-mangling-version=v0",
    "-C",
    "link-arg=-fuse-ld=rust-lld",
    "--cfg",
    "tokio_unstable",
    "--cfg",
    "windows_slim_errors",        # This cfg will reduce the size of `windows::core::Error` from 16 bytes to 4 bytes
    "-C",
    "target-feature=+crt-static", # This fixes the linking issue when compiling livekit on Windows
]
